site: Landon J. Getz - Blog
creator: Landon J. Getz
# Permalinks
relative_permalinks: false
permalink: "pretty"

# Setup
title:            Dr. Landon J. Getz
tagline:          'Curriculum Vitae'
description:      'ğŸ³ï¸â€ğŸŒˆ PhD. Research Scientist studying <i>Vibrio</i> species, with a keen interest in science ethics and policy.'
baseurl:          https://landongetz.com/

author:
  name:           'Landon J. Getz'
  url:            https://twitter.com/landongetz

# Custom vars
version:          'August 12th/2022'

lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

twitter_username: landongetz
